http:
  port: 8081

hooks:
  - name: "Example"
    requirements:
      ref: "refs/heads/example-project"
      repository:
        full_name: "BtheDestroyer/tiny-webhook"
    action:
      cwd: "../project"
      command: "git pull && make all && make run"

log:
  file: "./last.log"
  levels:
    errors: true
    warnings: true
    info: true
    debug: false
  web-portal:
    enabled: true
    count: 20
